FROM python:3.11-slim
WORKDIR /app
COPY requirements-test.txt requirements-test.txt
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements-test.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY . .

CMD ["pytest", "tests"]
